### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by ajonp** [zeit/ng-deploy-now#7]
Error: An unhandled exception occurred: Cannot find module 'now-client'
```
[error] Error: Cannot find module 'now-client'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ajonp/web/JAMStackGR/JAMStackGR-Deploy-v-GIT/node_modules/@zeit/ng-deploy/dist/builders/actions/deploy.js:18:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
I tried on both v8 and v9 Angular

**Comment by mugan86** [comment]
try to install 5.2.1 version of now-client package
`npm install now-client@5.2.1 `
The last version not compile need index.js script

**Comment by ajonp** [comment]
This for sure worked, maybe we should update the README or add it as a dependency? I will add a pull request ;)
